passage:
  - frame_id: "arena"
    position_x: 30.0
    position_y: 15.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0
    
  - frame_id: "arena"
    position_x: 30.0
    position_y: 35.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0

  - frame_id: "arena"
    position_x: 20.0
    position_y: 25.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0

  - frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    orientation_x: 0.0
    orientation_y: 0.0
    orientation_z: 0.0
    orientation_w: 1.0