# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the facades, but only active per trial.
arena:
  x_min: 0.0
  x_max: 50.0
  y_min: 0.0
  y_max: 40.0

building:
  x_min: 20.0
  x_max: 30.0
  y_min: 15.0
  y_max: 25.0
  first_floor: 5.0
  second_floor: 10.0

fire:
  
  - sub_type: "facadefire"
    frame_id: "arena"
    position_x: 30.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0
    
  - sub_type: "facadefire"
    frame_id: "arena"
    position_x: 30.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0
    
  - sub_type: "facadefire"
    frame_id: "arena"
    position_x: 30.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0
    
passage:
  - sub_type: "ground"
    frame_id: "arena"
    position_x: 30.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0
    
  - sub_type: "ground"
    frame_id: "arena"
    position_x: 30.0
    position_y: 35.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "ground" 
    frame_id: "arena"
    position_x: 20.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "ground"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "ground"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "first"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0

  - sub_type: "second"  
    frame_id: "arena"
    position_x: 40.0
    position_y: 25.0
    position_z: 0.1
    yaw: 0.0
    