mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['left_front_wheel_joint','left_rear_wheel_joint']
  right_wheel: ['right_front_wheel_joint','right_rear_wheel_joint']
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  wheel_separation : 0.585
  wheel_radius : 0.155

# Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true


 
