%YAML:1.0
---
histogram: !!opencv-matrix
   rows: 32
   cols: 1
   dt: f
   data: [ 4.38060286e-03, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 9.95619357e-01 ]
