# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the facades, but only active per trial.
arena:
  x_min: 0
  x_max: 60
  y_min: 0
  y_max: 50

building:
  x_min: 30
  x_max: 40
  y_min: 20
  y_max: 30
  x_base_min: 20
  first_floor: 5
  second_floor: 10

path:
  [
    [0, 3.3],
    [-2, 6],
    [-2, 20],
    [-5, 20],
    [-5, 6],
    [-8, 6],
    [-8, 20],
    [-11, 20],
    [-11, 6],
    [4, 6],
    [4, 20],
    [1, 20],
    [1, 6],
    [-2, 6]
  ]