# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the piles, but only active per trial.
arena:
  x_min: -20
  x_max: 30
  y_min: 0
  y_max: 50

uav_pile_zone:
  x_min: 0
  x_max: 40
  y_min: 0
  y_max: 21

ugv_pile_zone:
  x_min: -25
  x_max: 0
  y_min: 0
  y_max: 21

uav_wall_zone:
  x_min: 0
  x_max: 40
  y_min: 21
  y_max: 40

ugv_wall_zone:
  x_min: -25
  x_max: 0
  y_min: 21
  y_max: 42

# pile:
#   - color: "red"
#     sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: 15.0
#     position_y: 4.5
#     position_z: 0.1
#     yaw: 0.0

#   - color: "green"
#     sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: 15.0
#     position_y: 6.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "blue"
#     sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: 15
#     position_y: 7.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "orange"
#     sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: 15.0
#     position_y: 8.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "red"
#     sub_type: "ugv"
#     status: "active"
#     frame_id: "arena"
#     position_x: -7.0
#     position_y: 7.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "green"
#     sub_type: "ugv"
#     status: "active"
#     frame_id: "arena"
#     position_x: -9.0
#     position_y: 7.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "blue"
#     sub_type: "ugv"
#     status: "active"
#     frame_id: "arena"
#     position_x: -11.0
#     position_y: 7.0
#     position_z: 0.1
#     yaw: 0.0

#   - color: "orange"
#     sub_type: "ugv"
#     status: "active"
#     frame_id: "arena"
#     position_x: -13.0
#     position_y: 7.0
#     position_z: 0.1
#     yaw: 0.0

# wall:
#   - sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: -16.0
#     position_y: 22.0
#     position_z: 0.8
#     scale_x: 0.4
#     scale_y: 4.0
#     scale_z: 1.7
#     yaw: -2.35

#   - sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: -13.0
#     position_y: 22.0
#     position_z: 0.8
#     scale_x: 0.4
#     scale_y: 4.0
#     scale_z: 1.7
#     yaw: -0.78
  
#   - sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: -10.2
#     position_y: 22.0
#     position_z: 0.8
#     scale_x: 0.4
#     scale_y: 4.0
#     scale_z: 1.7
#     yaw: -2.35
  
#   - sub_type: "uav"
#     status: "active"
#     frame_id: "arena"
#     position_x: -7.1
#     position_y: 22.0
#     position_z: 0.8
#     scale_x: 0.4
#     scale_y: 4.0
#     scale_z: 1.7
#     yaw: -0.78




#  - sub_type: "ugv"
#    frame_id: "arena"
#    position_x: 30.0
#    position_y: 15.0
#    position_z: 0.1
#    yaw: 0.0
#    scale_x: 4.0
#    scale_y: 4.0
#    scale_z: 0.5
    
