# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the piles, but only active per trial.
arena:
  x_min: 0
  x_max: 60
  y_min: 0
  y_max: 50

uav_pile_zone:
  x_min: 30
  x_max: 60
  y_min: 0
  y_max: 25

ugv_pile_zone:
  x_min: 0
  x_max: 30
  y_min: 0
  y_max: 25

uav_wall_zone:
  x_min: 30
  x_max: 60
  y_min: 25
  y_max: 50

ugv_wall_zone:
  x_min: 0
  x_max: 30
  y_min: 25
  y_max: 50

pile:
  - color: "red"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 42.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0

  - color: "green"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 41.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0

  - color: "blue"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 39.5
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0

  - color: "orange"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 39.0
    position_y: 15.0
    position_z: 0.1
    yaw: 0.0

  - color: "red"
    sub_type: "ugv"
    status: "active"
    frame_id: "arena"
    position_x: 25.0
    position_y: 12.0
    position_z: 0.1
    yaw: 0.0

  - color: "green"
    sub_type: "ugv"
    status: "active"
    frame_id: "arena"
    position_x: 25.0
    position_y: 11.0
    position_z: 0.1
    yaw: 0.0

  - color: "blue"
    sub_type: "ugv"
    status: "active"
    frame_id: "arena"
    position_x: 25.0
    position_y: 10.0
    position_z: 0.1
    yaw: 0.0

  - color: "orange"
    sub_type: "ugv"
    status: "active"
    frame_id: "arena"
    position_x: 25.0
    position_y: 9.0
    position_z: 0.1
    yaw: 0.0

wall:
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 38.1
    position_y: 32.2
    position_z: 1.7
    yaw: -1.57

  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 40.0
    position_y: 30.0
    position_z: 1.7
    yaw: -3.14
  
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 42.2
    position_y: 28.1
    position_z: 1.7
    yaw: -1.57
  
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: 44.1
    position_y: 25.9
    position_z: 1.7
    yaw: -3.14

#  - sub_type: "ugv"
#    frame_id: "arena"
#    position_x: 30.0
#    position_y: 15.0
#    position_z: 0.1
#    yaw: 0.0
    
