# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the facades, but only active per trial.
arena:
  x_min: 0
  x_max: 60
  y_min: 0
  y_max: 50

building:
  x_min: 30
  x_max: 40
  y_min: 20
  y_max: 30
  x_base_min: 20
  first_floor: 5
  second_floor: 10

path:
  [
    [0, 0],
    [0, 15],
    [-5, 15],
    [-5, 3],
    [-10, 3],
    [-10, 15],
    [0, 0]
  ]