# Include only objects whose positions we know, even if they are inactive. For instance, if we have several possible poses for the piles, but only active per trial.
arena:
  x_min: -20
  x_max: 30
  y_min: 0
  y_max: 50

uav_pile_zone:
  x_min: 0
  x_max: 40
  y_min: 0
  y_max: 21

ugv_pile_zone:
  x_min: -25
  x_max: 0
  y_min: 0
  y_max: 21

uav_wall_zone:
  x_min: 0
  x_max: 40
  y_min: 21
  y_max: 40

ugv_wall_zone:
  x_min: -25
  x_max: 0
  y_min: 21
  y_max: 42

pile:
  - color: "red"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -10.17
    position_y: 12.75
    position_z: 0.1
    scale_x: 0.9
    scale_y: 8
    scale_z: 0.20
    yaw: 1.57

  - color: "green"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -10.17
    position_y: 14.25
    position_z: 0.1
    scale_x: 0.9
    scale_y: 8
    scale_z: 0.20
    yaw: 1.57

  - color: "blue"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -10.17
    position_y: 15.25
    position_z: 0.1
    scale_x: 0.2
    scale_y: 8
    scale_z: 0.20
    yaw: 1.57

  - color: "orange"
    sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -10.17
    position_y: 15.85
    position_z: 0.1
    scale_x: 0.2
    scale_y: 8
    scale_z: 0.20
    yaw: 1.57

wall:
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -14.74
    position_y: 23.32
    position_z: 0.8
    scale_x: 0.4
    scale_y: 4.0
    scale_z: 1.7
    yaw: -2.35

  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -11.92
    position_y: 23.37
    position_z: 0.8
    scale_x: 0.4
    scale_y: 4.0
    scale_z: 1.7
    yaw: -0.78
  
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -9.075
    position_y: 23.42
    position_z: 0.8
    scale_x: 0.4
    scale_y: 4.0
    scale_z: 1.7
    yaw: -2.35
  
  - sub_type: "uav"
    status: "active"
    frame_id: "arena"
    position_x: -6.295
    position_y: 23.47
    position_z: 0.8
    scale_x: 0.4
    scale_y: 4.0
    scale_z: 1.7
    yaw: -0.78

