# PID params for Ardupilot setPose pose control
pid:
  ros: false
  x:
    kp: 0.6
    ki: 0.0
    kd: 0.0
    min_sat: -1.0
    max_sat: 1.0
    min_wind: -2.0
    max_wind: 2.0
  y:
    kp: 0.6
    ki: 0.0
    kd: 0.0
    min_sat: -1.0
    max_sat: 1.0
    min_wind: -2.0
    max_wind: 2.0
  z:
    kp: 0.5
    ki: 0.0
    kd: 0.0
    min_sat: -1.0
    max_sat: 1.0
    min_wind: -2.0
    max_wind: 2.0
  yaw:
    kp: 0.4
    ki: 0.04
    kd: 0.0
    min_sat: -1.0
    max_sat: 1.0
    min_wind: -1.57
    max_wind: 1.57