%YAML:1.0
---
histogram: !!opencv-matrix
   rows: 32
   cols: 1
   dt: f
   data: [ 2.73351669e-02, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 9.72664893e-01 ]
