<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="atrvjr">
    <xacro:macro name="atrvjr" params="armConnectionFrame">


    <xacro:property name="M_PI" value="3.14159"/>
    <!-- Robot parameters -->
    <xacro:property name="center_height" value="0.1525" />
    <!-- This is not including the bumpers -->
    <xacro:property name="chassis_length" value="0.64" />
    <!-- This is including the bumpers -->
    <xacro:property name="chassis_length_bumpers" value="0.78" />
    <!-- This is not including the wheels -->
    <xacro:property name="chassis_width" value="0.385" />
    <!-- This is not including equipment and racks on the top -->
    <xacro:property name="chassis_height" value="0.52" />


        <!-- wheel properties -->
    <xacro:property name="wheel_radius" value="0.155" />
    <xacro:property name="wheel_width" value="0.095" />
    <xacro:property name="wheel_long_offset" value="0.19 " /> <!-- distance from robot center to wheel center in x direction (forward direction) -->
    <xacro:property name="wheel_lat_offset" value="0.25" /> <!-- distance from robot center to wheel center in y direction (lateral direction) -->


    <xacro:include filename="$(find atrvjr_description)/urdf/atrvjr_wheels.xacro" />

    <!-- mbot wheel generation based on imported macro -->
    <xacro:wheel prefix="front" side="left" origin_x="-${wheel_long_offset}" origin_y="${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="front" side="right" origin_x="${wheel_long_offset}" origin_y="${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="rear" side="left" origin_x="-${wheel_long_offset}" origin_y="-${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="rear" side="right" origin_x="${wheel_long_offset}" origin_y="-${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <!-- links -->
    <!-- base_link -->
    <!-- The frame of the floor directly below the center_link and -->
    <!-- is needed for the navigation stack to work properly -->
    <link name="base_link">
       <!--  <inertial>
            <origin xyz="0 0.3 0.2" rpy="1.57 0 0"/>
            <mass value="100"/>
            <inertia ixx="1.00" ixy="0.0" ixz="0.0" iyy="1.01" iyz="0.0" izz="1.01"/>
        </inertial> -->
    </link>

    <!-- center_link -->
    <!-- The link that is the origin of all of the components of the -->
    <!-- robot and should also represent the main chassis via inertial, -->
    <!-- visual, and geometry elements of the link -->
    <link name="center_link">
        <visual>
            <geometry>
                <mesh filename="package://atrvjr_description/meshes/atrv_body.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.1 0.25 0.19" rpy="0 0 0" /> 
            <geometry>
                <box size="${chassis_length} ${chassis_width+0.07} ${chassis_height-0.13}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.1 0.25 0.2" rpy="1.57 0 0"/>
            <mass value="1000"/>
            <inertia ixx="2.01" ixy="0.0" ixz="0.0" iyy="2.01" iyz="0.0" izz="2.01"/>
        </inertial>
    </link>

    <!-- base_link -> center_link -->
    <joint name="base_link_joint" type="fixed">
        <origin xyz="-0.1 0.19 ${center_height-0.1}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="center_link"/>
    </joint>

     <!-- Arm Link -->
    <link name="${armConnectionFrame}"/>

    <joint name="$to_{armConnectionFrame}_joint" type="fixed">
        <origin xyz="0.12 0 0.56" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="${armConnectionFrame}"/>
    </joint>

    <!-- Crossbow Imu Link -->
    <link name="cbimu_frame"/>

    <joint name="base_cbimu_joint" type="fixed">
        <origin xyz="0 0 0.267" rpy="0 ${M_PI} 0"/>
        <parent link="center_link"/>
        <child link="cbimu_frame"/>
    </joint>

        <!-- MPU Imu Link -->
    <link name="mpuimu_frame"/>

    <joint name="base_mpuimu_joint" type="fixed">
        <origin xyz="0 0 0.35" rpy="0 0 ${M_PI/2.0}"/>
        <parent link="center_link"/>
        <child link="mpuimu_frame"/>
    </joint>


    <!-- Hokuyo Link -->
    <link name="lrf_frame"/>

    <joint name="lrf_joint" type="fixed">
        <origin xyz="0.2 0 0.35" rpy="0 0 0"/>
        <parent link="center_link"/>
        <child link="lrf_frame"/>
    </joint>

    <!-- Hokuyo Link -->
    <link name="novatel"/>

    <joint name="novatel_joint" type="fixed">
        <origin xyz="-0.15 0.1 0.4" rpy="0 0 0"/>
        <parent link="center_link"/>
        <child link="novatel"/>
    </joint>

    </xacro:macro>
</robot>

