#goal definition
uint8 HOVER=0
uint8 GOTO=1
uint8 PICK=2
uint8 command
geometry_msgs/PoseStamped goto_target
---
#result definition
bool success
---
#feedback
geometry_msgs/PoseStamped current_pose
# geometry_msgs/PoseStamped target
