#goal definition
geometry_msgs/PoseStamped origin
float32 vertical_distance
float32 min_horizontal_distance
float32 max_horizontal_distance
float32 inc_horizontal_distance
float32 horizontal_velocity  # positive values indicates ccw, negative cw
---
#result definition
string message
---
#feedback
float32 rho
geometry_msgs/PoseStamped current_target
