std_msgs/Header header
geometry_msgs/PoseWithCovariance pose
geometry_msgs/Point relative_position
float32 relative_yaw
geometry_msgs/Vector3 scale
int8 type
int8 color

int8 TYPE_UNKNOWN = -1
int8 TYPE_BALL    =  0
int8 TYPE_BRICK   =  1
int8 TYPE_FIRE    =  2
int8 TYPE_PASSAGE =  3

int8 COLOR_UNKNOWN = -1
int8 COLOR_RED     =  0
int8 COLOR_GREEN   =  1
int8 COLOR_BLUE    =  2
int8 COLOR_ORANGE  =  3
