<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="atrvjr">
    <xacro:macro name="atrvjr" params="armConnectionFrame">


    <xacro:property name="M_PI" value="3.14159"/>
    <!-- Robot parameters -->
    <xacro:property name="center_height" value="0.1525" />
    <!-- This is not including the bumpers -->
    <xacro:property name="chassis_length" value="0.64" />
    <!-- This is including the bumpers -->
    <xacro:property name="chassis_length_bumpers" value="0.78" />
    <!-- This is not including the wheels -->
    <xacro:property name="chassis_width" value="0.385" />
    <!-- This is not including equipment and racks on the top -->
    <xacro:property name="chassis_height" value="0.45" />


        <!-- wheel properties -->
    <xacro:property name="wheel_radius" value="0.155" />
    <xacro:property name="wheel_width" value="0.095" />
    <xacro:property name="wheel_long_offset" value="0.19 " /> <!-- distance from robot center to wheel center in x direction (forward direction) -->
    <xacro:property name="wheel_lat_offset" value="0.25" /> <!-- distance from robot center to wheel center in y direction (lateral direction) -->


    <xacro:include filename="$(find atrvjr_description)/urdf/atrvjr_wheels.xacro" />

    <!-- mbot wheel generation based on imported macro -->
    <xacro:wheel prefix="front" side="left" origin_x="${wheel_long_offset}" origin_y="${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="front" side="right" origin_x="${wheel_long_offset}" origin_y="-${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="rear" side="left" origin_x="-${wheel_long_offset}" origin_y="${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel prefix="rear" side="right" origin_x="-${wheel_long_offset}" origin_y="-${wheel_lat_offset}" >
        <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:wheel>



   <!--  <link name="teste_link">

        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="teste_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="teste_link"/>
        <axis xyz="1 0 0"/>
        <limit effort="80.0" lower="-2" upper="2" velocity="0.5"/>
    </joint>
 -->
<!-- 
    <link name="teste2_link">
        <collision>
            <origin xyz="0.0 0.0 0.3" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height-0.05}" />
            </geometry>
        </collision> 
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="teste2_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="teste_link"/>
        <child link="teste2_link"/>
        <axis xyz="0 1 0"/>
        <limit effort="80.0" lower="-2" upper="2" velocity="0.5"/>
    </joint> -->


    <!-- links -->
    <!-- base_link -->
    <!-- The frame of the floor directly below the center_link and -->
    <!-- is needed for the navigation stack to work properly -->
    <link name="base_link">

        <inertial>
            <origin xyz="0.0 0.0 0.2" rpy="0 0 0"/>
            <mass value="55"/>
            <inertia ixx="3.15" ixy="0.0" ixz="0.0" iyy="4.1" iyz="0.0" izz="4.47"/>
        </inertial>
    </link>

    <!-- center_link -->
    <!-- The link that is the origin of all of the components of the -->
    <!-- robot and should also represent the main chassis via inertial, -->
    <!-- visual, and geometry elements of the link -->
    <link name="center_link">
        <visual>
            <geometry>
                <mesh filename="package://atrvjr_description/meshes/atrv_body.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.08 0.25 0.19" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width+0.05} ${chassis_height-0.05}" />
            </geometry>
        </collision>
    </link>

    <!-- base_link -> center_link -->
    <joint name="base_link_joint" type="fixed">
        <origin xyz="-0.1 0.19 ${center_height-0.1}" rpy="1.57 0 0"/>
        <parent link="base_link"/>
        <child link="center_link"/>
    </joint>




     <!-- Arm Link -->
    <link name="${armConnectionFrame}"/>

    <joint name="$to_{armConnectionFrame}_joint" type="fixed">
        <origin xyz="0.09 0 0.47" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="${armConnectionFrame}"/>
    </joint>

    <!-- Crossbow Imu Link -->
    <link name="cbimu_frame"/>

    <joint name="base_cbimu_joint" type="fixed">
        <origin xyz="0 0 0.267" rpy="0 ${M_PI} 0"/>
        <parent link="base_link"/>
        <child link="cbimu_frame"/>
    </joint>

        <!-- MPU Imu Link -->
    <link name="mpuimu_frame"/>

    <joint name="base_mpuimu_joint" type="fixed">
        <origin xyz="0 -0.1 0.55" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="mpuimu_frame"/>
    </joint>

    <link name="novatel"/>

    <joint name="novatel_joint" type="fixed">
        <origin xyz="-0.15 0.1 0.55" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="novatel"/>
    </joint>


    <link name="hokuyo"/>
<!--         <visual>
            <geometry>
                <box size="0.02 0.035 0.002"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
        </inertial>
    </link> -->

    <joint name="laser_joint" type="fixed">
        <origin xyz="0.37 0 0.135" rpy="${M_PI} 0 0"/>
        <parent link="base_link" />
        <child link="hokuyo" />
    </joint>

   <!--  <transmission name="teste_prismatic_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="teste_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="teste_prismatic_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="teste2_prismatic_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="teste2_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="teste2_prismatic_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission> -->


    </xacro:macro>
</robot>
