mbzirc_comm_objs/WallBluePrint wall_map
geometry_msgs/PoseStamped red_pile
geometry_msgs/PoseStamped green_pile
geometry_msgs/PoseStamped blue_pile
geometry_msgs/PoseStamped orange_pile
string uav_frame
string gripper_frame
---
bool success
