%YAML:1.0
---
histogram: !!opencv-matrix
   rows: 32
   cols: 1
   dt: f
   data: [ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 9.99999940e-01, 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0. ]
