<?xml version="1.0"?>
<robot name="iris" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="bar_l"           default="1.0"/>
  <xacro:arg name="bar_r"           default="0.005"/>
  <xacro:arg name="bar_mass"        default="0.005"/>

  <xacro:arg name="ball_r"          default="0.07"/>
  <xacro:arg name="ball_colour"     default="Gazebo/Red"/>
  <xacro:arg name="ball_mass"       default="0.09"/>

  <!-- Instantiate robots_description iris -->
  <xacro:include filename="$(find robots_description)/models/iris/model.xacro" />

  <!-- Bar-ball system -->
  <link name="base_union">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.005"/>
      <inertia ixx="1e-06" ixy="0" ixz="0" iyy="1e-06" iyz="0" izz="9e-06"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.0005" length="0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.0005" length="0.001"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_link_to_base_union_joint" type="continuous">
    <origin xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <parent link="base_link"/>
    <child link="base_union"/>
  </joint>

  <link name="bar">
    <inertial>
      <origin xyz="0 ${$(arg bar_l)/2} 0" rpy="1.5707963267948966 0 0"/>
      <mass value="${arg bar_mass}"/>
      <inertia ixx="${(1/12)*${arg bar_mass}*(3*${arg bar_r}*${arg bar_r}+${arg bar_l}*${arg bar_l})}" ixy="0" ixz="0" iyy="${(1/12)*${arg bar_mass}*(3*${arg bar_r}*${arg bar_r}+${arg bar_l}*${arg bar_l})}" iyz="0" izz="${(1/12)*${arg bar_mass}*(3*${arg bar_r}*${arg bar_r}+${arg bar_l}*${arg bar_l})}"/>
    </inertial>
    <visual>
      <origin xyz="0 ${$(arg bar_l)/2} 0" rpy="1.5707963267948966 0 0"/>
      <geometry>
        <cylinder radius="${arg bar_r}" length="$(arg bar_l)"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${$(arg bar_l)/2} 0" rpy="1.5707963267948966 0 0"/>
      <geometry>
        <cylinder radius="${arg bar_r}" length="$(arg bar_l)"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_union_to_bar_joint" type="continuous">
    <origin xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <parent link="base_union"/>
    <child link="bar"/>
  </joint>

  <link name="ball">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${arg ball_mass}"/>
      <inertia ixx="${(2/5)*${arg ball_mass}*${arg ball_r}*${arg ball_r}}" ixy="0" ixz="0"
               iyy="${(2/5)*${arg ball_mass}*${arg ball_r}*${arg ball_r}}" iyz="0" izz="${(2/5)*${arg ball_mass}*${arg ball_r}*${arg ball_r}}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="$(arg ball_r)"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <sphere radius="$(arg ball_r)"/>
      </geometry>
    </collision>
  </link>
  <joint name="ball_joint" type="fixed">
    <origin xyz="0 ${$(arg bar_l) + $(arg ball_r)} 0"/>
    <parent link="bar"/>
    <child link="ball"/>
  </joint>
  <gazebo reference="ball">
    <material>$(arg ball_colour)</material>
  </gazebo>

</robot>
